### PR TITLE
Google phishlet

### PR DESCRIPTION
**Pull request by TomAbel**
- Replace the botguard token with an error.

- Fix the password regex so it won't capture the captcha token if captcha is present. 

- Redirect to myaccount.google.com when tokens captured.

- Remove useless code and use placeholders correctly.

Editing the token enables the password form, which none of the phishlets currently achieve. Replacing it with an error is great because it doesn't require getting a valid token.

There's still some extra checks implemented when you attempt to login from a new location (email me if you have any info on that). The phishlet won't bypass those checks but it works on my machine

¯\_(ツ)_/¯

### CODE REVIEW

**Comment by athena2001** [comment]
before trying can you type in pw?

**Comment by TomAbel** [comment]
It will work if you're using it on your own account or an account which has logged in with the same IP as evilginx2 in the last 24hrs

**Comment by athena2001** [comment]
> It will work if you're using it on your own account or an account which has logged in with the same IP as evilginx2 in the last 24hrs

check ur email please lol

**Comment by TomAbel** [comment]
Requests are error-ing 400, something is wrong. Will patch soon

**Comment by Aleksandr3313** [comment]
WARN: Cannot handshake client accounts.google.com remote error: tls: unknown certificate вот ошибку которую надо устранить на данной Google phishlet № 657 и она должна заработать. Как это сделать незнаю

**Comment by Anonymoushawk** [comment]
hi @TomAbel Great work. 
But still it is workable only with an account which has logged in with the same IP ?

**Comment by TomAbel** [comment]
I don't know, people are saying it's not working at all. I bought some prepaid SIM cards for the purpose of testing it with freshly created accounts, but I don't know when I'll have time for it. You can use my fork in the meanwhile

**Pull request closed without merging**
