### PR TITLE
Evi ginix error 

### PR DESCRIPTION
**Pull request by cipher-ux**
provided configuration directory path does not exist: /root/.evilginx

### CODE REVIEW

**Comment by gelabertdionisio432** [comment]
Can anyone help me please i have this version of evilginx /hash3liZer/evilginx2 and i can not update it to acme v2.
Can you anyone show me how to do it?

Please reply me at: gelabert.dionisio432@gmail.com

**Comment by alvarezjcruiz9098** [comment]
> provided configuration directory path does not exist: /root/.evilginx error please how do i fix

It still doesn't work  even with the modifications made in main.go. Is it working for anyone else?

**Comment by gelabertdionisio432** [comment]
This is the version i have: go get -u github.com/hash3liZer/evilginx2
And is still not working.
Can you please help me?

**Comment by maykiproseg** [comment]
Google this patch gives some error on some or many accounts. how can i get this error

This browser or app may not be secure. Learn more

Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in.

**Comment by icq744701700** [comment]
Your Google phishlet needs update

**Comment by maykiproseg** [comment]
what kind of update, i added everything needed

**Comment by icq744701700** [comment]
Phishlet

**Comment by icq744701700** [comment]
Use my icq

**Comment by maykiproseg** [comment]
I understood that much What should I add.

**Comment by maykiproseg** [comment]
I don't use icq.

**Comment by maykiproseg** [comment]
how do you get this error
 Refused to display 'https://accounts.youtube.com/accounts/CheckConnection?pmpo=https%3A%2F%2Faccounts.google.com&v=-932230565&timestamp=1583407099695' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors https://accounts.google.com".

**Comment by pretech86** [comment]
i run the tool and can catch the password but ther's no token and i recieved the following error 

2020/03/29 06:15:19 [019] WARN: Cannot handshake client static.xx.fbcdn.net remote error: tls: bad certificate

also the facebook page not like the real one , please help me this is the 5th day i try the tool 
my email: sad.noscom@yahoo.com

**Comment by pretech86** [comment]
Now , i can catch the password and token and it’s working fine with me but the only problem the certification .. it always said bad certificate and the browser give a security alarm ... and the facebook page not like the real one but finally it working and i can catch the  token ... any body can help me please sad.noscom@yahoo.com

**Comment by pretech86** [comment]
Which domain provider is compatible with automatic lets encrypt ? And working good with evilginx2

**Comment by pretech86** [comment]
dears finally i solve the problem and get certification and enable it but the problem now when i try to use the link it not work , any body can help me .... sad.noscom@yahoo.com
lures

**Comment by pretech86** [comment]
how can i get gmail and yahoo phishlets

**Comment by pretech86** [comment]
dears i still get encrypted password and not cpmplete token for facebook , any body can help me ?

**Comment by suv0094** [comment]
> 
> 
> I'm getting this error too. it does not work anymore
> acme: error: 400 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-acct :: urn:ietf:params:acme:error:malformed :: No embedded JWK in JWS header, url:

does anyone has solution for this error? im getting error like this too

**Pull request closed without merging**
