### PR TITLE
Adding onelogin phishlet

### PR DESCRIPTION
**Pull request by perfectlylogical**
New Phishlet: OneLogin

OneLogin phishlet that will handle any combination of the following OneLogin configurations

1. Using custom CSS on the login page.
2. Using the default OneLogin login page.
3. Using the multi step login process (/login2/)
4. Using the single form login process (/login/)
5. Force "Keep me signed in" on /login urls

### CODE REVIEW

**Comment by oaredece** [comment]
Where is this onelogin ?

**Comment by oaredece** [comment]
Sorry for my bad comment ..just wake up. Please add me icq 10777333 for some personal questions. I have a very interesting project

**Comment by 744701700** [comment]
> right.. here i have some problem with my phishltes.. please leave me a skype, icq , something

744701700

**Comment by kgretzky** [comment]
Thanks @perfectlylogical for contribution! 🎉

**Pull request merged**
