### PR TITLE
Facebook : Fix Javascript and New Domains

### PR DESCRIPTION
**Pull request by charlesbel**
As Facebook made a new user interface, I corrected the phishlet to match the new login forms. Like instagram, I added some js to delay the login and send the password unencoded before the real login.

### CODE REVIEW

**Comment by Rovinskyi64** [comment]
4835d059-a0d7-4c93-ac1b-d92eb26cf051
b8b41302-3a47-4f0e-a162-36420434b3ea
d4954d76-356f-4452-804d-114bef3cbcc3
Hello, This phishlet does not capture cookie tokens, only username and password. After re-entering it writes "Acces denied" and blocks the phishing page. Where is the solution?

**Comment by charlesbel** [comment]
> 
> 4835d059-a0d7-4c93-ac1b-d92eb26cf051
> b8b41302-3a47-4f0e-a162-36420434b3ea
> d4954d76-356f-4452-804d-114bef3cbcc3
> Hello, This phishlet does not capture cookie tokens, only username and password. After re-entering it writes "Acces denied" and blocks the phishing page. Where is the solution?

You probably made too many login attempts so your ip is temporarily banned, but I can confirm the phishlet works well

**Comment by charlesbel** [comment]
UPDATE : Facebook seems to have a fraud detection system like all big websites targeting by IP address, so I would recommend to not use IP of VPS of famous hosters. Instead, I would recommend residencial proxies.

**Comment by Web3villian666** [comment]
I had similar issues stuck on the first sign in page that's the old phishlets.... attually I got the latest .yaml off the author y'all can reach out to him on icq @mrgretzky to get issues fixed if needed.

**Pull request closed without merging**
