### PR TITLE
Add Google.yaml to phishlets

### PR DESCRIPTION
**Pull request by CooganCodes**

### CODE REVIEW

**Comment by amrnyz** [comment]
Doesn't seem to be working. Gets stuck and keeps loading infinitely after entering an email address

**Comment by kizzygit** [comment]
not working

**Comment by rkmc90** [comment]
Plz some one add Google phishlet for evilginx2

**Comment by rkmc90** [comment]
ya this one is not working it does not enter the mail id n gets stuck there

**Comment by Web3villian666** [comment]
I had similar issues stuck on the first sign in page that's the old phishlets.... attually I got the latest .yaml off the author y'all can reach out to him on icq @mrgretzky to get issues fixed if needed.

**Comment by AnthraxBPLLC** [comment]
Contact me at telegram if interested in a demo included https://t.me/anthraxlinkers we might exchange on something. who knows

**Comment by ghost** [comment]
google added

**Pull request closed without merging**
