### PR TITLE
Template to capture Amazon and Reddit sessions/credentials

### PR DESCRIPTION
**Pull request by customsync**
Tested and working against Reddit accounts with 2FA both enabled and disabled. Captures the session cookie and credentials successfully.

### CODE REVIEW

**Comment by customsync** [comment]
It's my pleasure! The least I can do in thanks for this awesome tool. I noticed the redirect issue as well, and might step through the authentication requests/responses a little more closely to see where exactly this is occurring as well. If you beat me to it, I'd love to know how you do it!

In the mean time, I will try to add one or two more phishlets that are a little more self explanatory in the next week or two.

**Comment by customsync** [comment]
There's one for Amazon. I spent a little more time focusing on the redirect to make sure that works properly this time!

**Comment by kgretzky** [comment]
Just tested your Amazon phishlet! Works amazingly well! Congratulations!

I will merge them both into the repository and you can submit a PR for Reddit redirect fix, whenever you're ready. Great job!

**Comment by customsync** [comment]
@yahirlevine Thank you! With the information provided, it's hard to tell what's happening on your end. I've tested the Amazon phishlet specifically across multiple browsers and OS'. If you have your certificates and DNS records for your domain set properly along with the use of the URL generated from the "phishlets get-url" command, it should be working properly. 

Plus, once you have a session and credentials - that's all you really need! Testing out the other phishlets may help you get a feel for how the rewrites and redirects are happening. Good luck in working with it!

**Comment by kgretzky** [comment]
@customsync I've just tested and I can reproduce this behavior. After importing the cookies captured by Evilginx, Amazon shows that I am logged in, but indeed when I go to `My Account -> Your Orders` it will try to re-authenticate with 2FA and all that.

I think there may be some additional cookie that needs capturing, which makes the browser session trusted.

Let me know if you're able to reproduce.

**Comment by Herostere** [comment]
Hello, 
I have an issue with the captured passwords. In the session the entry for password is "true" but not the value of the password.
Is that an issue? Thank you.

**Comment by pretech86** [comment]
Please tell , this tool work with you , i have an issue with tls and acme ?

**Comment by Herostere** [comment]
@pretech86 You should give me your e-mail, to avoid flooding here :)

**Comment by pretech86** [comment]
Sad.noscom@yahoo.com

**Comment by PinkPantherX** [comment]
I've tried Amazon phishlet and it captures credentials but it doesn't capture cookies! Anyway to fix this issue?

**Comment by pretech86** [comment]
@pinkpantherx 

Kindly can i know which domain provider you use to generate the certificate without any problem ? Hope to help me !

**Pull request merged**
