### PR TITLE
Evilnginx With Webpanel on port 4000 nodejs and a nodejs script send logs into email 

### PR DESCRIPTION
**Pull request by AnthraxBPLLC**
Hi [kgretzky],  I want to share some scripts that I found around GitHub, an nginx panel that I have been fixing based on @an0nud4y phishlets repository web panel that I modified and improved able to copy cookies from the web panel with cookies based on Jason format pop up styles all you have to do is copy the cookies into editor and its already based on Jason format.

And a Data-puller based on nodejs that can send the details of the cookies on data. db based on crontab and can ship to telegram too and email edit the .env file into your smtp and your webhook details the email function it keeps checking the data. db for an update every 2 min. If there's an update, it will aauto-scheduleit. Every 2 min will deliver updated data.db cookies into your Email and Webhook telegram or discords. By doing this, command

Install nodejs:

curl -fsSL https://deb.nodesource.com/setup_19.x | bash - &&\
apt-get install -y nodejs
Install yarn:

npm i -g yarn

Install dependencies:

cd data-forwarder
mkdir install
yarn install

Copy .env.example to .env:

cp .env.example .env

Modify your .env file (config file):

nano .env
Run the app:

node app.js

If you want to run the app every minute to check for changes in the data.db file, add this to your crontab:

* * * * * node app.js >/dev/null 2>&1

### CODE REVIEW

**Comment by AnthraxBPLLC** [comment]
This Evilngnx version is based on @Cgboal Webhook version Mix with a main branch from @kgretzky  and modified with web panel @An0nUD4Y that I been fixed to copy cookies based on jason format at panel IP:4000 and a nodejs data puller that I call that based on nodejs it monitors the data.db every 2 min it will auto crontab it if there's a new update on data.db and send to your email and webhook service

**Comment by AnthraxBPLLC** [comment]
https://prnt.sc/D3wOgz3Za69K

**Comment by lhost25** [comment]
> This Evilngnx version is based on @Cgboal Webhook version Mix with a main branch from @kgretzky and modified with web panel @An0nUD4Y that I been fixed to copy cookies based on jason format at panel IP:4000 and a nodejs data puller that I call that based on nodejs it monitors the data.db every 2 min it will auto crontab it if there's a new update on data.db and send to your email and webhook service

How did you achieved this? I got the webpanel right but how do i make it send to email or telegram? Thanks @AnthraxBPLLC

**Comment by AnthraxBPLLC** [comment]
planning to give an update real soon

**Comment by Marksmart12** [comment]
Hello I want you to spam for me so that I can get good results office 365
or any good business logs.
Can we work together?

**Pull request closed without merging**
