### PR TITLE
Update Instagram Phishlet - Unencoded Password

### PR DESCRIPTION
**Pull request by charlesbel**
Since Instagram added an encryption tool on his passwords, the passwords are sended encoded and evilginx get it encoded. Just added a request in javascript to send anywhere the unencoded password and the evilginx get it unencoded.

### CODE REVIEW

**Comment by An0nUD4Y** [comment]
@charlesbel  , I think the same should work with facebook as well..
I have done that in different way, Check facebook phihslet [here](https://github.com/An0nUD4Y/evilginx2/blob/master/phishlets/facebook.yaml) 

Reach me on [Telegram](https://t.me/its_udy) , or leave yours

**Comment by An0nUD4Y** [comment]
@charlesbel , Thanks For This PR, I have also created a working Facebook Phishlet.
You Can add that in this PR.
[Phishlet Here](https://github.com/An0nUD4Y/Evilginx2-Phishlets/blob/master/facebook.yaml)

**Comment by charlesbel** [comment]
@An0nUD4Y I just Pulled a new request on the repo with the facebook phishlet. Thanks !

**Comment by kgretzky** [comment]
Thanks @charlesbel . Great job on the phishlet!

**Comment by pretech86** [comment]
it didn't catch the password

**Comment by charlesbel** [comment]
> it didn't catch the password 

Check the network tab of your browser to find an unsuccessful request to /ajax made by the js, if you didn't find it, the problem is somewhere else

**Comment by pretech86** [comment]
one more question .. how many free certificate lets encrypt provide now ?

**Comment by pretech86** [comment]
is lets encrypt make any update to prevent generate the certificate autmatically from evilginx as before because i cant generate it like before

**Comment by pretech86** [comment]
when i try login from mobile it redirect me directly to the redirect url and not landed to facebook page

**Comment by charlesbel** [comment]
> when i try login from mobile it redirect me directly to the redirect url and not landed to facebook page

This is why your request is unauthorized, so use a lures link to access it and it gonna work

**Comment by An0nUD4Y** [comment]
@charlesbel , Out Of Topic...

Do you Have any idea why the google invisible recaptcha v3 is being failed after reverse proxing it.

**Comment by pretech86** [comment]
@charlesbel i used lures link already

**Comment by charlesbel** [comment]
> @charlesbel i used lures link already 

This error is from evilginx, not from phishlets, check evilginx logs

**Comment by charlesbel** [comment]
> @charlesbel , Out Of Topic...
> 
> Do you Have any idea why the google invisible recaptcha v3 is being failed after reverse proxing it.

I think google have a cross-origins security, so when it is proxied, evilginx keep this security, and the domain is not authorized so it fail

**Comment by pretech86** [comment]
> > @charlesbel i used lures link already
> 
> This error is from evilginx, not from phishlets, check evilginx logs

 unauthorized request

**Comment by charlesbel** [comment]
> 
> > > @charlesbel i used lures link already
> > 
> > This error is from evilginx, not from phishlets, check evilginx logs
> 
>  unauthorized request

So the lures url is not correct and evilginx refuse the request, open an issue if you did not find the way to fix

**Comment by pretech86** [comment]
> 
> 
> > > > @charlesbel i used lures link already
> > > 
> > > 
> > > This error is from evilginx, not from phishlets, check evilginx logs
> > 
> > 
> > unauthorized request
> 
> So the lures url is not correct and evilginx refuse the request, open an issue if you did not find the way to fix

it redirect me to a youtube page which was the redirect page for the default old facebook phishlet and this youtube page not my redirect url

**Comment by charlesbel** [comment]
> > 
> > 
> > > > > @charlesbel i used lures link already
> > > > 
> > > > 
> > > > This error is from evilginx, not from phishlets, check evilginx logs
> > > 
> > > 
> > > unauthorized request
> > 
> > So the lures url is not correct and evilginx refuse the request, open an issue if you did not find the way to fix
> 
> it redirect me to a youtube page which was the redirect page for the default old facebook phishlet and this youtube page not my redirect url

Out of topic... This is an error of config, refere to the docs

**Comment by pretech86** [comment]
also for google2 phishlets the hosts of it contain some repeated hosts isit normal and what the difference between googl and ggogle2 phishlets 

 accounts.google2
 www.google2
ssl.google2
content.google2
www.google2
 mail.google2
 myaccount.google2
 drive.google2
 ssl.google2
 ssl.google2
 ssl.google2
 play.google2
 ogs.google2
 notifications.google2
apis.google2
accounts.google2
 fonts.google2
 lh3.google2
 accounts.google2
 accounts.google2
 www.google2
 fonts.google2
 www.google2

**Comment by charlesbel** [comment]
> also for google2 phishlets the hosts of it contain some repeated hosts isit normal and what the difference between googl and ggogle2 phishlets 
> 
>  accounts.google2
>  www.google2
> ssl.google2
> content.google2
> www.google2
>  mail.google2
>  myaccount.google2
>  drive.google2
>  ssl.google2
>  ssl.google2
>  ssl.google2
>  play.google2
>  ogs.google2
>  notifications.google2
> apis.google2
> accounts.google2
>  fonts.google2
>  lh3.google2
>  accounts.google2
>  accounts.google2
>  www.google2
>  fonts.google2
>  www.google2
> 

The google phishlets does not exist in this repo, you downloaded it from another one, please refere to where you downloaded it

**Comment by An0nUD4Y** [comment]
> 
> 
> > @charlesbel , Out Of Topic...
> > Do you Have any idea why the google invisible recaptcha v3 is being failed after reverse proxing it.
> 
> I think google have a cross-origins security, so when it is proxied, evilginx keep this security, and the domain is not authorized so it fail

Did you tried to create any phishlet with google recaptcha v3 enabled ?

**Comment by charlesbel** [comment]
> > > @charlesbel , Out Of Topic...
> > > Do you Have any idea why the google invisible recaptcha v3 is being failed after reverse proxing it.
> > 
> > 
> > I think google have a cross-origins security, so when it is proxied, evilginx keep this security, and the domain is not authorized so it fail
> 
> Did you tried to create any phishlet with google recaptcha v3 enabled ?

Not for the moment : )

**Comment by pretech86** [comment]
facebook phishlet still not catch the password and the lures link blocked the account

**Comment by pretech86** [comment]
its working from laptop and i still trying on my phone .. best regards

**Comment by pretech86** [comment]
it catch the token but stil cant catch the password

**Pull request merged**
