### PR TITLE
All ACME 400 401 402 403 errors

### PR DESCRIPTION
**Pull request by tutanota**
All these errors are due to the lack of communication with the nameserver, the different handling of digitalocean and the freenom page when the dns are specifically administered, the assignment of ns1.example.com and ns2.example.com to the server's ip where the evilginx2 is run has no response connection I use godday as a company to register my domain but due to their policy of administering the dns just like any other company that manages them that way will result in such errors, correct if I'm wrong

### CODE REVIEW

**Comment by pretech86** [comment]
i get this error can any body help me 

 failed to load certificate files for phishlet 'facebook', domain 'facebook.contactsocialmedia.com': open /root/.evilginx/crt/facebook.contactsocialmedia.com/facebook.crt: no such file or directory

**Comment by tutanota** [comment]
> i get this error can any body help me
> 
> failed to load certificate files for phishlet 'facebook', domain 'facebook.contactsocialmedia.com': open /root/.evilginx/crt/facebook.contactsocialmedia.com/facebook.crt: no such file or directory

yes gimme a mail to help you

**Comment by pretech86** [comment]
@tutanota sad.noscom@yahoo.com 

Please help me 4 days until now and I couldn’t solve this issue , i try every things

**Comment by pretech86** [comment]
I solve the problem .. and i can catch the password but in session I didn’t find the token and the password

**Comment by pretech86** [comment]
Now , i can catch the password and token and it’s working fine with me but the only problem the certification .. it always said bad certificate and the browser give a security alarm ... and the facebook page not like the real one but finally it working and i can catch the token ... any body can help me please sad.noscom@yahoo.com

**Comment by pretech86** [comment]
i get an ssl certificate and put it in ./evilginx/crt/ and it working well , and when i run apache2 and check the certificate it run correctly with no error and the browser trust my domain , but when i stop apache2 and run evilginx the browser still not trust the certificate and the facebook page not like the real one 

please any one can help me sad.noscom@yahoo.com

**Comment by pretech86** [comment]
Finally i solve the problem and it’s working well thanks for this great tool , really thanks

**Comment by pretech86** [comment]
why i get encrypted password and not get token 

 Password: AQBQAIRGkv9spktL1YWdY55eZmOnW2yUbjRYoFeEumxxAH1yAozxCXGKe3FkdiX+zgO611G8TQreBoD8Kea2NAMY600UGNdisU1uw82PARc/swnpdeQcJ9sOYRZ9P+NaY 

any body help me

**Comment by J35t3rOP** [comment]
Screenshot_2020-05-02_20-20-15
help please.. i cannot find any solution

**Comment by jepunband** [comment]
hello i'm getting this error:
acme: error: 400 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-acct :: urn:ietf:params:acme:error:malformed :: No embedded JWK in JWS header, url:

**Comment by jepunband** [comment]
> Finally i solve the problem and it’s working well thanks for this great tool , really thanks any body need any help i can help him for free

@pretech86  how to solve this:

acme: error: 400 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-acct :: urn:ietf:params:acme:error:malformed :: No embedded JWK in JWS header, url:

**Comment by fbracon** [comment]
how to resolve this :_
acme: error: 400 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-acct :: urn:ietf:params:acme:error:malformed :: No embedded JWK in JWS header, url:

**Comment by Shivammalaviya** [comment]
[10:01:19] [war] failed to load certificate files for phishlet 'outlook', domain 'outlook.usmicrosoft.com': open /root/.evilginx/crt/outlook.usmicrosoft.com/outlook.crt: no such file or directory

Can someone please help me ?

**Comment by Shivammalaviya** [comment]
> 
> 
> > Finally i solve the problem and it’s working well thanks for this great tool , really thanks any body need any help i can help him for free
> 
> @pretech86 how to solve this:
> 
> acme: error: 400 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-acct :: urn:ietf:params:acme:error:malformed :: No embedded JWK in JWS header, url:

Can you please me in this ?

**Comment by aminesated** [comment]
> > > Finally i solve the problem and it’s working well thanks for this great tool , really thanks any body need any help i can help him for free
> > 
> > 
> > @pretech86 how to solve this:
> > acme: error: 400 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-acct :: urn:ietf:params:acme:error:malformed :: No embedded JWK in JWS header, url:
> 
> Can you please me in this ?

Can you help me please, I have the same problem

**Comment by aminesated** [comment]
> Finally i solve the problem and it’s working well thanks for this great tool , really thanks any body need any help i can help him for free

Can you help me please? I have the same problem

**Comment by jxhnxy** [comment]
: phishlets enable outlook
[09:59:12] [inf] enabled phishlet 'outlook'
[09:59:12] [inf] setting up certificates for phishlet 'outlook'...

[09:59:12] [war] failed to load certificate files for phishlet 'outlook', domain 'm.plshackmelord.xyz': open /root/.evilginx/crt/m.plshackmelord.xyz/outlook.crt: no such file or directory

[09:59:12] [inf] requesting SSL/TLS certificates from LetsEncrypt...

[09:59:29] [!!!] acme: Error -> One or more domains had a problem:
[account.m.plshackmelord.xyz] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for account.m.plshackmelord.xyz - check that a DNS record exists for this domain, url:

[login.m.plshackmelord.xyz] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for login.m.plshackmelord.xyz - check that a DNS record exists for this domain, url:

[outlook.m.plshackmelord.xyz] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for outlook.m.plshackmelord.xyz - check that a DNS record exists for this domain, url:

[09:59:29] [inf] disabled phishlet 'outlook'

I'm a newbie here, please can someone tell me what I'm doing wrong?

**Comment by jayhill365** [comment]
https://1jayhill.medium.com/evilginx2-x-gophish-to-hunt-for-2fa-mfa-passwords-cookies-using-aws-godaddy-f03e9154732b this might help out.

**Pull request closed without merging**
