### PR TITLE
Phishlet for protonmail

### PR DESCRIPTION
**Pull request by JamesCullum**
Tested on FF & Chrome, with and without 2FA. Will disable 2FA and rely on credentials instead of cookies.

### CODE REVIEW

**Comment by kgretzky** [comment]
Thanks! Looks amazing. 

One question, if you disable 2FA through the changes to the UI and capture the credentials only, it would still be NOT possible to login with these, because 2FA is enabled on the account?

I understand that the phishlet allows you to capture the credentials, but still it does not provide access to the account if 2FA is enabled, right?

Oh btw, can you also change the `name` value to `protonmail` or something like that?

**Comment by JamesCullum** [comment]
Not sure what you mean, so let me try to explain the two possible user flows.

Generally, the phishlet captures the login credentials in-memory when logging in.

Scenario 1) User has no 2FA enabled

The phishlet recognizes that the normal inbox appears after the login without any 2FA prompt. It then leaks the cached credentials immediately.

Scenario 2) User has 2FA enabled

The phishlet recognizes that 2FA is prompted after the login. Once the user fills that in and the mailbox pops up, it will change the UI and force the user to disable 2FA. After that is done, the user is redirected to the normal interface without visible changes. The cached credentials get leaked then.

P.S.: Changed the name, thanks for the hint.

**Comment by kgretzky** [comment]
Ok, thanks for explanation! So your phishlet tricks the user to disable 2FA if it is enabled?

I can see the JS code is commented out. Shouldn't it be put into the `js_inject` block for it to be injected into the landing page?

**Comment by JamesCullum** [comment]
It's somewhere between "tricking" and "forcing", yes.

The JS is minified and appended into the body in the proxy filters. Using `js_inject` from my understanding requires that JS variables are set, isn't it? As I want the script to be enabled by default and it didn't work for O365, I thought it was the easiest to add it into the body directly.

The commented code is mostly so people don't get weirded out from having minified javascript in the phishlet and the code can later be maintained more easily.

**Comment by kgretzky** [comment]
Sounds great!

Yes it can be like this, it's fine.
If you don't specify the required parameters for `js_inject` the JS will be injected by default, so the outcome will be the same.

Let me know if you want me to merge right away and I'll do it.

**Comment by JamesCullum** [comment]
If changes are needed later on I might revisit it, but for now it's fine this way and you are free to merge 👍

**Comment by kgretzky** [comment]
It's all good! Thanks!

**Pull request merged**
