### PR TITLE
FIX Dockerfile with go mod

### PR DESCRIPTION
**Pull request by antoineVIVIES**
I have modified the docker to be able to launch it with the go mod

### CODE REVIEW

**Comment by phra** [comment]
any update?

**Comment by jrozner** [comment]
Can this get merged?

**Comment by unicorn-art** [comment]
@antoineVIVIES
"Go.pkg copy failed" what that mean?
I try to install with docker in my server

**Comment by antoineVIVIES** [comment]
@unicorn-art 
Which Dockerfile did you try to use?
Try to use mine if you used the repository one.

**Comment by Anthirian** [comment]
I just used your version of the Dockerfile after the one in master errored out on me. Thanks for fixing it. I could build the image successfully on OpenSUSE Tumbleweed. This seems to be okay to merge.

**Comment by kgretzky** [comment]
Thank you guys for testing this! Merging it in.

**Pull request merged**
