### PR TITLE
evilginx2

### PR DESCRIPTION
**Pull request by d3v3lop3rtuta**

### CODE REVIEW

**Comment by Blackselection** [comment]
Hi guys,

dont know how to open a new pull request, this while I will try to report my actual problem here.
Annoying to find this problem in google, searching since 5 hours to find a solution.

: phishlets enable linkedin
[13:13:54] [inf] enabled phishlet 'linkedin'
[13:13:54] [inf] setting up certificates for phishlet 'linkedin'...
[13:13:54] [war] failed to load certificate files for phishlet 'linkedin', domain 'hidden': open /root/.evilginx/crt/hidden/linkedin.crt: no such file or directory
[13:13:54] [inf] requesting SSL/TLS certificates from LetsEncrypt...
[13:13:55] [!!!] acme: error: 400 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-acct :: urn:ietf:params:acme:error:malformed :: No embedded JWK in JWS header, url:                          
[13:13:55] [inf] disabled phishlet 'linkedin'                               

getting this error everytime...did somebody know how to solve it or what I am doing wrong ?

**Comment by macha1212** [comment]
I exactly have the same problem !

**Comment by pretech86** [comment]
So what we will do my friend 😃


Sent from Yahoo Mail for iPhone


On Tuesday, May 12, 2020, 11:04 AM, macha1212 <notifications@github.com> wrote:




I exactly have the same problem !

**Comment by macha1212** [comment]
Did you install the certificate ? I think that the problem

Le mar. 12 mai 2020, à 04 h 12, pretech86 <notifications@github.com> a
écrit :

**Comment by pretech86** [comment]
I already installed the certificate automatically and it working but i get some error like bad authentication with one domain

**Comment by pretech86** [comment]
I install the certificate automatically with no error but get encrypted passwords

**Comment by macha1212** [comment]
Was looking to do it with certbot Ill let you know !


Le mar. 12 mai 2020, à 14 h 05, pretech86 <notifications@github.com> a
écrit :

**Comment by macha1212** [comment]
btw are you a white hat or black hat hahaha

**Comment by An0nUD4Y** [comment]
@pretech86 ,
Get The Fixed Phishlets Here ...
https://github.com/An0nUD4Y/Evilginx2-Phishlets

**Comment by pretech86** [comment]
I can’t find your phishlet

**Comment by jepunband** [comment]
hello i have just installed the latest version of evilginx2 with Go... i'm getting this error :

acme: error: 400 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-acct :: urn:ietf:params:acme:error:malformed :: No embedded JWK in JWS header, url:

**Comment by Bishu005** [comment]
Can anyone teach me to create a Linkedin phishlet perfectly, I don't understand what is wrong and everytime I do I couldn't make real linkedin phishlet

**Comment by Sniper1470** [comment]
@Bishu005 add me up on telegram on ICQ @714653641 i can help you out with the linkedin phislets creation

**Comment by Bishu005** [comment]
Hello Sniper I couldn't find you on Telegram, Could you provide your
username again, Thanks

**Comment by Sniper1470** [comment]
add me @piperberlesimo on telegram

**Pull request closed without merging**
